IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Migrations')
BEGIN
    CREATE TABLE Migrations (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        ScriptName NVARCHAR(256) NOT NULL UNIQUE,
        AppliedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END
